### ISSUE TITLE
README mentions file that does not exists

### ISSUE THREAD

**Issue by smartel99** [kiwih/cubeide-sd-card#4]
At point 2 and 3 of the **Adoption Guide** section of the readme, the file `FATFS/Target/user_spi.c` is mentioned. However, in my own testing (using an STM32L452), this file is called `FATFS/Target/user_diskio.c`. 

This might just be a thing with the STM32L4 CubeMX package generating the files differently, but I felt like it was worth mentioning.

**Comment by kiwih** [comment]
Good eye, thanks! That probably comes from my original version of this codebase, I later went through tidying everything up, must have missed those points.
